name: flutter_common_exports
description: A Flutter package includes some common exportation of constants and utils.
version: 0.1.1
homepage: https://github.com/AlexVincent525/flutter_common_exports

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  oktoast: ^2.3.2
  intl: any

flutter:
  uses-material-design: true