name: flutter_common_exports
description: A Flutter package includes some common exportation of constants and utils.
version: 0.1.0
homepage: https://github.com/AlexVincent525/flutter_common_exports

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartx: ^0.4.1
  oktoast: 2.3.2

dependency_overrides:
  dartx: ^0.4.1
  intl: ^0.16.1

flutter:
  uses-material-design: true