name: flutter_common_exports
description: A Flutter package includes some common exportation of constants and utils.
version: 0.1.0
homepage: https://github.com/AlexVincent525/flutter_common_exports

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  oktoast: 2.3.2
  pedantic: 1.9.0
  permission_handler: 5.0.0+hotfix.6

dependency_overrides:
  dartx: ^0.4.1
  intl: ^0.16.1

flutter:
  uses-material-design: true